apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sample-app
  name: sample-app
spec:
  containers:
  - image: profiling-api:8.0
    name: sample-app
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
