apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    run: sample-app
  name: sample-app-nodeport
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 30080
  selector:
    run: sample-app
  type: NodePort
status:
  loadBalancer: {}
